### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by MockbaTheBorg** [z-rui/luaffi#1]
Hi there ... I am trying to build this on armhf platform and getting errors.
Maybe the arm platform code is bad?
I just want to know if this is still maintained so I can move further on troubleshooting.

**Comment by z-rui** [comment]
Hi, I wrote this for fun and it isn't actively maintained.  That said, I just tried compiling it on amd64 Linux and it works fine.  The sample code (except gtk2.lua, which is not portable) works.

Feel free to clone the repo and adapt for your use case.  If you have specific error messages to share, I might be able to take a look when I got time :-)

**Comment by z-rui** [comment]
Rewrote the codebase.  If you still want to use it, please give it a try.  I'll try to resolve any problems.  Closing this bug.
I'm maintaining it with my personal time.  So maintenance is best-effort, no guarantee :)
